g++ --std=c++20 \
-ggdb \
-fdiagnostics-show-template-tree \
-Werror \
-Wextra \
-Wall \
-Wpedantic \
-Wconversion \
-Warith-conversion \
-Wwrite-strings \
-Warray-bounds=2 \
-Wcast-align=strict \
-Wcast-qual \
-Wdouble-promotion \
-Wduplicated-branches \
-Wduplicated-cond \
-Wformat-overflow=2 \
-Wnull-dereference \
-Wimplicit-fallthrough=5 \
-Wshift-negative-value \
-Wswitch-default \
-Wswitch-enum \
-Wuninitialized \
-Wfloat-equal \
-Wshadow \
-Wlogical-op \
-Wvla \
-Wno-unknown-pragmas \
./src/chip8_emulator/chip8.cpp \
./tests/test.cpp \
-o bin/chip8.bin

